FROM node:21-alpine

WORKDIR /usr/src

# 安装 pnpm
RUN npm install -g pnpm@7

# 复制依赖文件
COPY package.json pnpm-lock.yaml .npmrc ./

# 安装依赖
RUN pnpm install

# 设置环境变量
ENV HOST=0.0.0.0 
ENV PORT=3000 
ENV NODE_ENV=development

# 暴露端口
EXPOSE $PORT

# 开发模式启动命令 (通过 docker-compose 覆盖)
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]