version: '3'

services:
  chatgpt-demo:
    build: .
    container_name: chatgpt-demo
    restart: always
    ports:
        - "3000:3000"
    environment:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL}